# Generated by Django 3.0.3 on 2020-05-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('paymode', 'user')},
        ),
    ]
